### ISSUE TITLE
Updating recipe to include fix for CVE-2022-29458

### ISSUE THREAD

**Issue by AndresGuzman-Ballen** [AnacondaRecipes/ncurses-feedstock#10]
It appears that updating ncurses-feedstock recipe to include fix for [CVE-2022-29458](https://nvd.nist.gov/vuln/detail/CVE-2022-29458) may be a bit complicated. The fix is specifically in the following commit: https://github.com/mirror/ncurses/commit/4c9f63c460cb7134f142aa65f6866c175ed77605. However, if I were to convert this commit alone to a patch and apply it to source code checked out using v6.3 tag, it fails.

Should ncurses-feedstock be updated where instead of checking out 6.3, it specifically checks out the snapshot at that particular commit to include the CVE fix? Even if that's possible, I imagine it's not the right approach because it no longer is 6.3 but 6.4.alpha. I don't know if this is one of those instances where fixing the CVE can only be done when ncurses v6.4 is made available.

@katietz @tobijk @chenghlee @remkade what are your thoughts?

**Comment by chenghlee** [comment]
We generally avoid packaging development and other non-release versions. The simplest solution may be to wait for the next ncurses release (be that 6.4 or 7.0). The [Red Hat](https://access.redhat.com/security/cve/CVE-2022-29458), [SUSE](https://www.suse.com/security/cve/CVE-2022-29458.html), and [Canonical](https://ubuntu.com/security/CVE-2022-29458) security teams have determined this is a much less severe vulnerability than the NVD CVSS score would suggest; in particular, these groups determined that the NVD assessment of high confidentiality impact is incorrect, and I am inclined to agree.

However, if you believe this is _really_ a major security concern, I would suggest extracting the specific fix out of the referenced commit, rather than trying to apply the entire patch set. Based on the commit message (and earlier changelog messages), the other bits of the patch set are ongoing development work for the next ncurses release. They likely depend on other changes made since the 6.3 release, which explains why they failed to apply; in any case, we would also not want to apply them since that could potentially put our package in a weird state that is not API- and/or ABI-compatible with the existing ncurses 6.3 packages nor with the upcoming releases.

**Comment by AndresGuzman-Ballen** [comment]
@chenghlee thank you for looking into this! That totally makes sense, and I imagine the security teams of Red Hat, SUSE, and Canonical know better than I do about the severity of the issue, so I will go ahead and close this ticket then and mark in our CI as a skippable CVE

**Comment by AndresGuzman-Ballen** [comment]
@chenghlee Turns out that Intel still wants this addressed so I created a PR that addresses the fix (and does not include all the other changes): https://github.com/AnacondaRecipes/ncurses-feedstock/pull/11
